### PR TITLE
Fixes reference list new lines

### LINKED ISSUE #3: Reference list accumulates "s"s"s on Windows
Via @taneliang

image

Bet this is because of Windows EOL characters messing up the replace measurement here:
https://github.com/foambubble/foam-vscode/blob/master/src/extension.ts#L164

Or, could be a different editor setting that doesn't insert newlines at the end of the file like mine does.

In either case, that login can be made more robust, the current implementation has too many failure modes

### PR DESCRIPTION
**Pull request by jevakallio**
Fixes number of issues related to reference list new lines. Closes #3 #5 #10

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -195,17 +208,18 @@ class WikilinkReferenceCodeLensProvider implements CodeLensProvider {
...
       return [];
     }
 
     return generateReferenceList(document).then((refs) => {
-      let status =
-        getText(range).replace(/\r?\n|\r/g, docConfig.eol) ===
-        refs.join(docConfig.eol)
-          ? "up to date"
-          : "out of date";
+      const oldRefs = getText(range).replace(/\r?\n|\r/g, docConfig.eol);
```
Comment (jevakallio) [inline src/extension.ts:219]: No logic changes here, just adding clarity

File: src/extension.ts [hunk 2]
```diff
@@ -195,17 +208,18 @@ class WikilinkReferenceCodeLensProvider implements CodeLensProvider {
     document: TextDocument,
     _: CancellationToken
   ): CodeLens[] | Thenable<CodeLens[]> {
+    loadDocConfig();
```
Comment (jevakallio) [inline src/extension.ts:211]: Ensuring that loadDocConfig is called even when CodeLens executes before other extension methods

File: src/extension.ts [hunk 3]
```diff
@@ -152,27 +162,26 @@ async function generateReferenceList(doc: TextDocument): Promise<string[]> {
...
+
+  if (headerLine >= footerLine) {
     return null;
   }
 
   return new Range(
-    new Position(header[0], header[1]),
-    new Position(footer[0], footer[1])
+    new Position(headerLine, 0),
+    new Position(footerLine, REFERENCE_FOOTER.length)
```
Comment (jevakallio) [inline src/extension.ts:184]: Previously we over-matched to the next line after footer, now we'll only read the footer length
